worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    ssl_protocols TLSv1.2 TLSv1.3;

    server {
        listen 0.0.0.0:8080 default_server;
        server_name _;

        return 200 "Unknown virtual host\n";
    }

    server {
        listen 0.0.0.0:8080;
        server_name aaa.st14.sne22.ru;

        root /usr/local/nginx/html/aaa;
        index index.html;
    }

    server {
        listen 0.0.0.0:8080;
        server_name bbb.st14.sne22.ru;

        root /usr/local/nginx/html/bbb;
        index index.html;
    }

    server {
        listen 0.0.0.0:8443 ssl default_server;
        server_name _;

        ssl_certificate     certs/aaa.st14.sne22.ru.crt;
        ssl_certificate_key certs/aaa.st14.sne22.ru.key;

        return 200 "Unknown virtual host\n";
    }

    server {
        listen 0.0.0.0:8443 ssl;
        server_name aaa.st14.sne22.ru;

        ssl_certificate     certs/aaa.st14.sne22.ru.crt;
        ssl_certificate_key certs/aaa.st14.sne22.ru.key;

        root /usr/local/nginx/html/aaa;
        index index.html;
    }

    server {
        listen 0.0.0.0:8443 ssl;
        server_name bbb.st14.sne22.ru;

        ssl_certificate     certs/bbb.st14.sne22.ru.crt;
        ssl_certificate_key certs/bbb.st14.sne22.ru.key;

        root /usr/local/nginx/html/bbb;
        index index.html;
    }
}
